
repos:
- repo: "https://github.com/psf/black"
  rev: "23.7.0"
  hooks:
  - id: "black"
    args: 
      - "src"
      - "tests"

- repo: "https://github.com/pycqa/isort"
  rev: "5.12.0"
  hooks:
  - id: "isort"
    args: 
      - "--py"
      - "311"
      - "--profile=black"
      - "src"
      - "tests"

- repo: "https://github.com/pycqa/flake8"
  rev: "6.1.0"
  hooks:
  - id: "flake8"
    args:
      - "src"
      - "tests"
