[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mazes"
version = "0.0.1"

dependencies = [
    "numpy ~=1.25",
]

[project.optional-dependencies]
dev = [
    "pytest ~=7.4.0",
]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
