[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mazes"
version = "0.0.1"
requires-python = ">=3.11"

dependencies = [
]

[project.optional-dependencies]
dev = [
    "pytest ~=7.4.0",
]

[project.scripts]
maze = "mazes.cli:maze_cli"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
